### ISSUE TITLE
Browser not opened on Windows ARM64

### ISSUE THREAD

**Issue by mmunte-impeo** [michaellzc/better-opn#17]
Hello, 
I recently installed Windows ARM64 on a parallels VM to check compatibility of the devops chain we use. 

One issue I found is that the browser window does not open. I am using better-opn. 

Hence, this issue report. 

Thank you for this great package.

**Comment by ExiaSR** [comment]
would you provide more detail about your environment? such as OS version, browsers installed in your VM, etc. I am assuming you're running it on the new M1 MacBook?

**Comment by mmunte-impeo** [comment]
Hi, yes you are right - this is on a M1 Mac running Parallels 16 preview.

inside the VM:
Windows 10 pro insider
Build 21327 prerelease 210226-1427
Chrome 89.0.4389.82

I hope this helps

**Comment by ExiaSR** [comment]
When running on OS other than macOS, `better-opn` actually fallbacks to good old plain [open](https://github.com/sindresorhus/open), learn more from https://github.com/ExiaSR/better-opn/blob/master/src/index.js#L109

I noticed a few issues and PRs related to `windows` or `powershell` were closed in upstream, so the issue you experience may have been fixed already. I didn't really look into these issues, so I could be wrong.

Would you try installing the latest [v3](https://github.com/ExiaSR/better-opn/releases/tag/v3.0.0) release which uses the latest `open` package? I tested it on a Windows VM using parallel and it works fine. It's x86 tho, I don't have direct access to an M1 MacBook 😞

Please let me know if the issue still persists and provide more information. Unless our strategy to guess the current OS is wrong, we will need to open an issue in [open](https://github.com/sindresorhus/open). Therefore, I suggest taking another look at their repo if thing is still not working. 

- what "shell" are you running? such as WSL, WSL2, PowerShell, or cygwin (Is it still a thing)
