### ISSUE TITLE
Query on setting the default command shell

### ISSUE THREAD

**Issue by Darkmift** [michaellzc/better-opn#37]
Hi,

I came across an issue with running storybook which is dependant on this npm.

The issue lies in my IT restricting powershell...
I would apreciate some help letting me know how to set a diffrent shell for the use (the command arg in the image attached).

Please see attachment for more details

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at module.exports (C:\Users\akoenig\WORKSPACE\storybook-angular-testing-master\node_modules\better-opn\node_modules\open\index.js:175:34) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

![87878787](https://user-images.githubusercontent.com/12433441/149965864-f9620bbb-e093-4ada-b51f-2963c15808e8.PNG)

P.s.
I tried setting the defaut shell for npm but this had no effect...if anyone knows which config to edit and how so the command will path to another shell I would really appreciate the help.

Edit:

I tried to manually tweak the code but this failed,I lack the knowledge to make this work right

![987987987](https://user-images.githubusercontent.com/12433441/149970384-4ac8cb52-2fba-43a1-97e7-a9da58ecc4a4.PNG)

**Comment by michaellzc** [comment]
Hi @Darkmift,

Thanks for opening a bug-ish report.

`better-opn` only kicks in when it's run on macOS (`darwin`)
https://github.com/michaellzc/better-opn/blob/2594401bfabcb6d0ad01f76c32f273533dcdfb04/src/index.js#L53-L55
In your case, which is windows, it will always fallback to using the upstream https://github.com/sindresorhus/open  https://github.com/michaellzc/better-opn/blob/2594401bfabcb6d0ad01f76c32f273533dcdfb04/src/index.js#L109

I suggest looking it up existing issues at [sindresorhus/open](https://github.com/sindresorhus/open/issues?q=powershell), or opening a new issue against them.
